using System.Collections.Generic;
using Godot;

namespace OCT7.Game.Audio
{
    public enum SoundId
    {
        Rifle,
        MachineGun,
        Sniper,
        Cannon,
        RocketLaunch,
        Explosion,
    }

    /// <summary>
    /// All sound effects, cached for the whole session. A recording at res://assets/audio/{name}.wav or .ogg
    /// (names: rifle, machine_gun, sniper, cannon, rocket_launch, explosion) replaces the synthesized sound;
    /// otherwise a few procedural variants are generated by <see cref="SoundSynth"/> on first use.
    /// </summary>
    public static class SoundBank
    {
        private static readonly Dictionary<SoundId, AudioStream[]> Cache = new Dictionary<SoundId, AudioStream[]>();

        public static readonly SoundId[] All =
        {
            SoundId.Rifle, SoundId.MachineGun, SoundId.Sniper, SoundId.Cannon, SoundId.RocketLaunch, SoundId.Explosion,
        };

        public static string FileName(SoundId id)
        {
            switch (id)
            {
                case SoundId.Rifle: return "rifle";
                case SoundId.MachineGun: return "machine_gun";
                case SoundId.Sniper: return "sniper";
                case SoundId.Cannon: return "cannon";
                case SoundId.RocketLaunch: return "rocket_launch";
                default: return "explosion";
            }
        }

        public static int VariantCount(SoundId id) =>
            id == SoundId.Rifle || id == SoundId.MachineGun ? 4 : id == SoundId.Cannon || id == SoundId.RocketLaunch ? 2 : 3;

        /// <summary>True when a recording in res://assets/audio/ overrides the synthesized sound.</summary>
        public static bool IsOverridden(SoundId id) => LoadOverride(id) != null;

        public static AudioStream Get(SoundId id, int variant)
        {
            var variants = Variants(id);
            return variants[Mathf.PosMod(variant, variants.Length)];
        }

        /// <summary>Generates everything up front (call at match start so the first shot doesn't hitch).</summary>
        public static void Warm()
        {
            foreach (var id in All)
            {
                Variants(id);
            }
        }

        private static AudioStream[] Variants(SoundId id)
        {
            if (Cache.TryGetValue(id, out var cached))
            {
                return cached;
            }

            var file = LoadOverride(id);
            AudioStream[] result;
            if (file != null)
            {
                result = new[] { file };
            }
            else
            {
                result = new AudioStream[VariantCount(id)];
                for (int i = 0; i < result.Length; i++)
                {
                    result[i] = SoundSynth.Create(id, i);
                }
            }

            Cache[id] = result;
            return result;
        }

        private static AudioStream LoadOverride(SoundId id)
        {
            foreach (var ext in new[] { ".wav", ".ogg" })
            {
                string path = $"res://assets/audio/{FileName(id)}{ext}";
                if (ResourceLoader.Exists(path))
                {
                    return GD.Load<AudioStream>(path);
                }
            }

            return null;
        }

        /// <summary>Writes every synthesized variant as a WAV file (for previewing or as a starting point for edits).</summary>
        public static int ExportWavs(string directory)
        {
            DirAccess.MakeDirRecursiveAbsolute(directory);
            int written = 0;
            foreach (var id in All)
            {
                for (int i = 0; i < VariantCount(id); i++)
                {
                    var wav = SoundSynth.Create(id, i);
                    string path = System.IO.Path.Combine(directory, $"{FileName(id)}_{i + 1}.wav");
                    if (wav.SaveToWav(path) == Error.Ok)
                    {
                        written++;
                    }
                    else
                    {
                        GD.PushError($"[audio] could not write {path}");
                    }
                }
            }

            return written;
        }
    }
}
